apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: warmdiet-pvc
  namespace: warmdiet
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: alicloud-disk-ssd  # 阿里云 SSD 存储类